/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ParticlesImport } from './routes/particles'
import { Route as IndexImport } from './routes/index'
import { Route as LibsLibNameCompTypeCompNameImport } from './routes/libs.$libName.$compType.$compName'

// Create/Update Routes

const ParticlesRoute = ParticlesImport.update({
  id: '/particles',
  path: '/particles',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LibsLibNameCompTypeCompNameRoute =
  LibsLibNameCompTypeCompNameImport.update({
    id: '/libs/$libName/$compType/$compName',
    path: '/libs/$libName/$compType/$compName',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/particles': {
      id: '/particles'
      path: '/particles'
      fullPath: '/particles'
      preLoaderRoute: typeof ParticlesImport
      parentRoute: typeof rootRoute
    }
    '/libs/$libName/$compType/$compName': {
      id: '/libs/$libName/$compType/$compName'
      path: '/libs/$libName/$compType/$compName'
      fullPath: '/libs/$libName/$compType/$compName'
      preLoaderRoute: typeof LibsLibNameCompTypeCompNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/particles': typeof ParticlesRoute
  '/libs/$libName/$compType/$compName': typeof LibsLibNameCompTypeCompNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/particles': typeof ParticlesRoute
  '/libs/$libName/$compType/$compName': typeof LibsLibNameCompTypeCompNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/particles': typeof ParticlesRoute
  '/libs/$libName/$compType/$compName': typeof LibsLibNameCompTypeCompNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/particles' | '/libs/$libName/$compType/$compName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/particles' | '/libs/$libName/$compType/$compName'
  id: '__root__' | '/' | '/particles' | '/libs/$libName/$compType/$compName'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParticlesRoute: typeof ParticlesRoute
  LibsLibNameCompTypeCompNameRoute: typeof LibsLibNameCompTypeCompNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParticlesRoute: ParticlesRoute,
  LibsLibNameCompTypeCompNameRoute: LibsLibNameCompTypeCompNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/particles",
        "/libs/$libName/$compType/$compName"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/particles": {
      "filePath": "particles.tsx"
    },
    "/libs/$libName/$compType/$compName": {
      "filePath": "libs.$libName.$compType.$compName.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
